export const SITE = {
  website: "https://leeyc924.github.io/blog/",
  author: "leeyc",
  profile: "https://github.com/leeyc924",
  desc: "개발과 일상을 기록하는 블로그",
  title: "leeyc blog",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: false,
  postPerIndex: 10,
  postPerPage: 10,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: false,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "https://github.com/leeyc924/blog/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "ko",
  timezone: "Asia/Seoul",
} as const;
